<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="geografia_mundial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pais"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pais">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="continente" type="xs:string"/>
        <xs:element ref="capital"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="capital">
    <xs:complexType>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>